# Generated by Django 5.1 on 2024-11-04 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamificacao_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('idade', models.IntegerField()),
                ('email', models.CharField(max_length=60, unique=True)),
            ],
        ),
    ]
