# Generated by Django 5.1 on 2024-11-05 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamificacao_app', '0003_pessoaselo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PessoaAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_realizado', models.DateTimeField(auto_now_add=True)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamificacao_app.selo')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamificacao_app.pessoa')),
            ],
        ),
    ]
